input.onButtonPressed(Button.A, function () {
    wuKong.setAllMotor(50, 50)
    basic.pause(500)
    wuKong.setAllMotor(-10, 50)
    basic.pause(1000)
    wuKong.setAllMotor(73, 34)
    basic.pause(5000)
    wuKong.stopAllMotor()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    wuKong.stopAllMotor()
    basic.showNumber(2)
    radio.sendNumber(2)
    music._playDefaultBackground(music.builtInPlayableMelody(Melodies.PowerUp), music.PlaybackMode.InBackground)
})
radio.setTransmitPower(7)
radio.setGroup(2)
radio.setFrequencyBand(32)
basic.showNumber(2)
wuKong.setLightMode(wuKong.LightMode.OFF)
